name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app
    - name: Run tests
      run: xcodebuild clean test -project "PodLib.xcodeproj" -scheme "PodLib" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
