name: Swift

on:
  create:
    
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: (github.event_name == 'pull_request' && || contains(github.ref, '/tags/test/pr/'))|| (github.event_name == 'push' && (contains(github.ref, '/heads/master')))

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app
    - name: Run tests
      run: xcodebuild clean test -project "PodTest.xcodeproj" -scheme "PodUnitTests" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
