name: AutomatedTrigger

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app
    - name: Run tests
      run: xcodebuild clean test -project "PodTest.xcodeproj" -scheme "PodUnitTests" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push PodTestSom.podspec
